function model = model_tetheredpuck(params)
% model = model_tetheredpuck(params)
% Hybrid model file for a puck attached to a tether to demonstrate hybrid integrator
% framework. Returns a model structure to be passed to the
% hybrid_integrator function. 
%
% This file uses a spring-damper model for the puck contact
%
% See hybrid_integrator.pdf for specifications on the contents of the structure.
%
% Inputs: params, a structure containing the fields:
%	p.r: puck radius
%	p.m: puck mass
%	p.k: effective stiffness of tether in contact with puck


	% Dynamics for puck being propelled 
	model.propelled = struct(...
		'dynamics',{ @(t,x,F) dyn_1dofpropelled(t,x,F,params) },...
		'transition_events',{ {@(t,x,F) events_tetheredpuck_stretch(t,x,F,params)} },...
		'transition_to',{ {{'pogo'}} },...
		'transition_response',{ {{ [] }} },...
		'state_map',{ struct('pogo',{@state_map_identity}) },...
		'other_events',{ {@events_detect_max_distance} },...
		'other_events_response',{ {{ [] }} },...
		'integrator',{ @ode45 },...
		'integrator_options',{ {'Refine',10} }); %return more points on the trajectory
	

	% Dynamics for puck interacting with the tether via a spring/damper
	model.pogo = struct(...
		'dynamics',{ @(t,x,F) dyn_3dofpogo(t,x,F,params) },...
		'transition_events',{ {@(t,x,F) events_puckreturntest_launch(t,x,F,params)} },...
		'transition_to',{ {{'propelled'}} },...
		'transition_response',{ {{ [] }} },...
		'state_map',{ struct('propelled',{@state_map_identity}) },...
		'other_events',{ {} },...
		'other_events_response',{ {} },...
		'integrator',{ @ode45 },...
		'integrator_options',{ {'Refine',10} }); %return more points on the trajectory

end
